# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: retailOrg
    Domain: retail.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: anchor
        SANS:
          - localhost
      - Hostname: backup
        SANS:
          - localhost
    Users:
      Count: 1 #The number of user accounts _in addition_ to Admin
      Specs:
        - Name: retail
